version: "3.7"

networks:
  net:

services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    restart: "always"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/diggy.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - sandbox
    networks:
      - net

  web:
    build:
      context: .
      dockerfile: Dockerfile.repl
    ports:
      - 5000:5000
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./userland:/userland
    networks:
      - net

  sandbox:
    privileged: true
    ports:
     - 8060:8060
    init: true
    ipc: none
    tty: true
    working_dir: $PWD/diggy-sandbox
    env_file:
      - .env
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    build:
      context: .
      dockerfile: Dockerfile.sandbox
      args:
        DEV: 0
    volumes:
      - ./userland:/userland
    networks:
      - net

volumes:
  user-base:
